### ISSUE TITLE
v1.8.3 (+ Bridge 15) seems to fail at runtime - Bridge.initAssembly is not a function

### ISSUE THREAD

**Issue by DanTup** [ProductiveRage/Bridge.React#10]
I'm trying to use the new package with Bridge v15. Packages look like this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Bridge.Core" version="15.0.0" targetFramework="net461" />
  <package id="Bridge.Html5" version="15.0.0" targetFramework="net461" />
  <package id="Bridge.Min" version="15.0.0" targetFramework="net461" />
  <package id="Bridge.React" version="1.8.3" targetFramework="net461" />
</packages>
```

The JavaScript that gets output includes this (which I presume is pulled from JS embedded in the Bridge.React package?):

```js
Bridge.initAssembly("Bridge.React", function ($asm, globals) {
```

However this fails with:

> Uncaught TypeError: Bridge.initAssembly is not a function

I'm bundling scripts with `combineScripts` and my JS is thousands of lines long (it definitely includes the Bridge code) but I've searched my JS file and there is only one instance of `initAssembly` and it's the one above.

**Comment by ProductiveRage** [comment]
I accidentally released an update built against a preview version of Bridge 15.0 and a method "initAssembly" has been renamed to "assembly" within Bridge. I've pushed a fixed version to NuGet, it's just being indexed at the moment and so should be available for use within a few minutes.
