### ISSUE TITLE
Demos doesn´t work, problem with Attributes

### ISSUE THREAD

**Issue by YandyZaldivar** [ProductiveRage/Bridge.React#15]
I am reviewing this library and it doesn´t work for me. When I remove the use of Attributes on elements it works. For example:

Doesn´t works: `return DOM.Div(new Attributes { ClassName = "wrapper" }, ...`
Works: `return DOM.Div("AnyText" ...`

It happens with Div and other elements. I am using lastest version of Bridge 15.5.0.

**Comment by Zaid-Ajaj** [comment]
Hi @YandyZaldivar,

Please elaborate on what exactly did not work 

What demo have you tried? I have a working todo app with react and redux [Here](https://github.com/Zaid-Ajaj/ReactReduxTodoApp),  although for Bridge 15.3.0 

it is a compile error or  javascript run-time error?

**Comment by YandyZaldivar** [comment]
> What demo have you tried?
The demo on the readme file with an appropriate html file.

> it is a compile error or javascript run-time error?
It compiles fine on C#. I haven´t debugged any JavaScript, I am constrained on time right now. Basically React doesn´t work, but if you use the overload dom element creation method that doesn´t use Attributes it works.

I haven´t tested with other version of bridge than 15.5.0, but I suppose I can do that tomorrow or so.

Thanks.

**Comment by ProductiveRage** [comment]
It looks like Bridge 15.5 (released this week) has introduced some issues. I've fixed up a couple of them and released a new version of the NuGet package (Bridge.React 1.10.0), which is currently being indexed on nuget.org and so should be available soon.

I'm going to continue looking into this in case anything else has broken.

If you get a chance to try out the latest NuGet package tomorrow and let us know if it works or not for you, that would be appreciated.
