### ISSUE TITLE
NullReferenceException from Analyzer when running via msbuild

### ISSUE THREAD

**Issue by DanTup** [ProductiveRage/Bridge.React#19]
I don't currently have a stack trace for this, but buildserver logs are full of warnings about NREs in the analyzer:

> CSC : warning AD0001: Analyzer 'Bridge.React.Analyser.ReactElementAnalyser' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [D:\CI\W\BLAH\BLAH\BLAH.csproj]

In the middle of debugging something else, but will try and get a better error/stack when I have more time.

**Comment by ProductiveRage** [comment]
Is it doing this with the latest code?

Sounds similar to this:

https://forums.bridge.net/forum/community/help/3885-unexpected-warning-in-bridge-react

**Comment by ProductiveRage** [comment]
@DanTup Did you get a chance to follow up on my question? Hopefully this issue has already been addressed. Re-open the issue if not.

**Comment by DanTup** [comment]
Foolishly, I didn't keep a note of where I saw this. I can't find them in any logs now (not even from last week when I opened this!). It does look like exactly the same issue you linked to though, so I suspect it's fixed. If I see it again and I'll do more digging and get a better repro.
