### ISSUE TITLE
Drag event handlers accept MouseEvent instead of DragEvent as a parameter

### ISSUE THREAD

**Issue by Porl91** [ProductiveRage/Bridge.React#21]
Drag event handlers in the 'DomElementWithEventsAttributes' class accept MouseEvent objects as parameters rather than DragEvent objects.

You can see from the spec that the DragEvent class just derives from the MouseEvent class and exposes the 'DataTransfer' property:
https://www.w3.org/TR/2011/WD-html5-20110113/dnd.html#dragevent

I've been going dynamic in order to access the property until now. I'd expect the event handlers listed under 'Event Types' of the following page to accept DragEvent:

https://developer.mozilla.org/en-US/docs/Web/API/DragEvent

**Comment by ProductiveRage** [comment]
This has been addressed by the following changesets -

https://github.com/ProductiveRage/Bridge.React/commit/3a04b04dfb36144d6c50cdbbe66257ff55d0b21a

https://github.com/ProductiveRage/Bridge.React/commit/1e830d8de4b8148104aafadabab6eb0351c052bd

There are some other changes that I'm bundling together but hopefully this will be released next week.
