### ISSUE TITLE
InputAttributes.Autocomplete does not accept strings

### ISSUE THREAD

**Issue by DanTup** [ProductiveRage/Bridge.React#31]
(Raised a similar issue in Bridge at https://github.com/bridgedotnet/Bridge/issues/2970)

Currently the AutoComplete property on input attributes only accepts an enum with a value of On or Off, however it's valid to have arbitrary strings and also a set of defined ones (like `new-password` and `address-line1`, etc.):

https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#autofill-detail-tokens

Should this be `Union<string, AutoComplete>`?

**Comment by ProductiveRage** [comment]
Makes sense. I see that Bridge have already made the change on their end!
