### ISSUE TITLE
Moving from Bridge.Html5 to Retyped.dom

### ISSUE THREAD

**Issue by dnaustin** [ProductiveRage/Bridge.React#42]
Hello

Are there plans to move from Bridge.Html5 to Retyped.dom following @geoffreymcgill's [blog post](https://blog.bridge.net/bridge-17-0-beta-now-available-ab17c9eb8cfa) on the bridge.net website?

**Comment by ProductiveRage** [comment]
I have looked into it but I'm not happy to move over until this retyped issue is resolved:

https://github.com/Retyped/Retyped/issues/18

I think that it makes retyped.dom unusable currently.

It shouldn't be a huge amount of effort to change Bridge.React when it's fixed, though.

**Comment by dnaustin** [comment]
Good to know you are on the ball with it :) I'm just starting out using the library and following your very informative blog post series.

**Comment by ProductiveRage** [comment]
I'll reopen this when the Bridge Team fix that issue and I can pick up retyped again.
