### ISSUE TITLE
How to map ReactModal onRequestClose to Bridge.React?

### ISSUE THREAD

**Issue by kendallb** [ProductiveRage/Bridge.React#59]
I am building my own bindings for ReactModal, and to start with I disassembled the Retyped version to see how the automatic bindings handled it (not sure there is any other way to see the source for a generated Retyped library is there?). Anyway, I am stuck on the onRequestClose event based on the Typescript defs here (which are out of data, but that's a different issue):

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-modal/index.d.ts

The Typescript definition says that it can accept either a mouse or keyboard event like this:

```
onRequestClose?(event: (MouseEvent | KeyboardEvent)): void;
```

The Retyped bindings generate this:

```
public Action<Union<Html5.MouseEvent, Html5.KeyboardEvent>> OnRequestClose { get; set; }
```

But for Bridge.React there are different classes for the keyboard and mouse events. I think I need to map them to those events, so do I just change the function signature to this?

```
public Action<Union<MouseEvent<HTMLElement>, KeyboardEvent<HTMLElement>>> OnRequestClose { get; set; }
```

or is there something else I would need to do in order to have it be bound those event types rather than the Bridge.Html5 ones?

**Comment by ProductiveRage** [comment]
That looks correct. The reason that Bridge.React is different to retyped is that retyped sacrifice type information about CurrentTarget in events. I raised this with the Bridge Team a long time ago and they didn't want to change retyped.

**Comment by kendallb** [comment]
Ok thanks. The more I look at Retyped libraries the more I realize they are not that useful at all. Other than a starting point to build your own mappings.
