### ISSUE TITLE
Missing inline styles with attributes

### ISSUE THREAD

**Issue by Zaid-Ajaj** [ProductiveRage/Bridge.React#6]
According to [Inline Styles](https://facebook.github.io/react/tips/inline-styles.html) there should be a property of `Attributes` class called `style` which is missing.

**Comment by ProductiveRage** [comment]
There was a property "Style" on the "ReactDomElementAttributes" which the "Attributes" class is derived from - but it was of type "dynamic" and so there were no property types to make declaring inline styles particularly easy.

Following the changes in PR #8 (which you created - thank you!), I think we can consider this issue resolved. I need to release an updated version of the package to NuGet (which I hope to do within the next few days), other than that there is no more work required here.
